name: custom_date_range_picker
description: A Flutter package for both android and iOS which provides a custom date range picker
version: 1.0.11
homepage: https://github.com/El-Mazouzi/custom_date_range_picker

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
      
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^3.0.1

  flutter_test:
    sdk: flutter

flutter: null
